amfnd: Add missing braces [#1743]
Add missing braces to fix the following compilation error discovered when using
GCC 6:

compdb.cc: In function 'int comp_init(AVND_COMP*, const SaImmAttrValuesT_2**)':
compdb.cc:1579:2: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
  if (immutil_getAttr(const_cast<SaImmAttrNameT>("saAmfCompCSISetCallbackTimeout"), attributes,
  ^~
compdb.cc:1582:3: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   comp->use_comptype_attr->set(CsiSetCallbackTimeout);
   ^~~~
compdb.cc:1584:2: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
  if (immutil_getAttr(const_cast<SaImmAttrNameT>("saAmfCompCSIRmvCallbackTimeout"), attributes,
  ^~
compdb.cc:1587:3: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
   comp->use_comptype_attr->set(CsiRemoveCallbackTimeout);
   ^~~~