imm: Fix build failure on CentOS 6 [#1570]
Fix the following build problem which was seen on CentOS 6:

CXX      osafimmnd-ImmModel.o
In file included from ImmModel.cc:22:0:
ImmModel.hh:277:43: error: ?va_list? has not been declared
ImmModel.cc:9646:1: error: prototype for ?void ImmModel::setCcbErrorString(CcbInfo*, const char*, __va_list_tag*)? does not match any in class ?ImmModel?
In file included from ImmModel.cc:22:0:
ImmModel.hh:279:25: error: candidates are: void ImmModel::setCcbErrorString(CcbInfo*, const char*, ...)
ImmModel.hh:274:25: error:                 void ImmModel::setCcbErrorString(CcbInfo*, const char*, int)